In [1]:
import numpy as np

In [12]:
a=np.array([10,12,16,20])
b=np.array([1,1.2,1.5,2])

In [20]:
c=a/b;c

array([10.        , 10.        , 10.66666667, 10.        ])

In [21]:
c**2

array([100.        , 100.        , 113.77777778, 100.        ])

In [22]:
str(c)

'[10.         10.         10.66666667 10.        ]'

In [27]:
S=np.array([[10,10,10,10],[20,30,40,50]])
Y=np.array([[1,1,1,1],[2,3,4,5]])

In [57]:
S

array([[10, 10, 10, 10],
       [20, 30, 40, 50]])

In [65]:
S[0:,1:3]

array([[10, 10],
       [30, 40]])

In [52]:
a=np.sqrt([1,17,64,100]);a

array([ 1.        ,  4.12310563,  8.        , 10.        ])

In [54]:
np.floor(a)

array([ 1.,  4.,  8., 10.])

In [1]:
import numpy as np
new_trials=np.array([[10,15,17,19,21,25,27],[2,3,5,7,9,11,13]])

In [89]:
new_trials.ravel()

array([10, 15, 17, 19, 21, 25, 27,  2,  3,  5,  7,  9, 11, 13])

In [90]:
new_trials.resize(3,4)

ValueError: cannot resize an array that references or is referenced
by another array in this way.
Use the np.resize function or refcheck=False

In [104]:
np.hsplit(new_trials,1)

[array([[10, 15, 17, 19, 21, 25, 27],
        [ 2,  3,  5,  7,  9, 11, 13]])]

In [2]:
a1=np.array([2,3,4])
b1=np.array([20,30,40])
a1*10

array([20, 30, 40])

In [123]:
inv_array=np.array([[10,20],[15,25]]);inv_array

array([[10, 20],
       [15, 25]])

In [124]:
np.linalg.inv(inv_array)

array([[-0.5,  0.4],
       [ 0.3, -0.2]])

In [125]:
np.trace(inv_array)

35

In [131]:
np.dot(a1,b1)

290

In [3]:
(np.matrix(a1))

matrix([[2, 3, 4]])