In [1]:
import numpy as np

In [3]:
import scipy 

In [14]:
from scipy import linalg

In [15]:
matrix=np.array([[10,6],[2,7]])

In [17]:
matrix

array([[10,  6],
       [ 2,  7]])

In [21]:
inv_matrix=linalg.inv(matrix);inv_matrix

array([[ 0.12068966, -0.10344828],
       [-0.03448276,  0.17241379]])

In [24]:
linalg.det(matrix)

58.0

In [25]:
lin_eq=np.array([[30,50],[4,]])

In [26]:
lin_eq_value=np.array([21,9,6])

In [27]:
linalg.solve(lin_eq,lin_eq_value)

array([ 4.95,  4.35, -1.95])

In [ ]:
scipy.linalg.eig

In [1]:
from scipy.stats import norm

In [6]:
f=norm.rvs(loc=0,scale=1,size=10)

In [12]:
print(f)

[-0.30500603  1.28832987 -1.97521539  0.376298   -1.6274086   0.06057258
 -0.70072748 -1.07375216 -0.25523187 -1.11120229]


In [16]:
six_sig=norm.cdf(10,loc=0,scale=1)

In [18]:
import matplotlib

In [21]:
pyplot.plot(six_sig)

NameError: name 'pyplot' is not defined